# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Stenhouse
tagline:          'Work in progress'
description:      'Work in progress'
url:              https://stenhousems.github.io
baseurl:          /

author:
  name:           'Michael Stenhouse'
  url:            https://twitter.com/stenhousems

gems:             [jekyll-paginate]
paginate:         5
paginate_path:    "page:num"

# Custom vars
version:          2021.04
twitter:          https://twitter.com/stenhousems
github:           https://github.com/stenhousems
